language: java

addons:
  chrome: stable

before_install:
  - export DISPLAY=99:0
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - rm chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver 
   /usr/local/bin/chromedriver
  - sleep 3


script:
  - mvn -Dwebdriver.chrome.driver=//usr//local//bin//chromedriver clean test